### ISSUE TITLE
Problem installing with node 8.X

### ISSUE THREAD

**Issue by haas85** [jugglingdb/sqlite3-adapter#42]
Hi, I am trying this module with node 8.9 and I am having a problems when I tried to install it using node 8.9. It looks that your 0.1.0 version is published in npm repo with the dependency to sqlite3 version 3.1.4 which doesn't build on node 8.X but I have checked and the versions 3.1.8 and 3.1.13 does.

In your github repo you already have the dependency to sqlite3@3.1.8 added, so, would it be possible for you to publish that change to npm?

Thanks

**Comment by 1602** [comment]
Hi @haas85. Thanks for reporting! It's not that easy unfortunately, because I updated sqlite3-adapter in a not compatible way, so jugglingdb update is required. I'll check what I can do in jugglingdb core to unblock this. Hopefully will find some time this weekend.

**Comment by haas85** [comment]
Awesome! Lots of thanks!

**Comment by 1602** [comment]
@haas85 good news I've published 1.0.0 which has been rewritten quite a bit recently, hence bumping major version. Not-so-good news is that it _might_ not work with current stable jugglingdb version. I need to find more free time to confirm that and implement the fix.

**Comment by haas85** [comment]
Nice! If you want I can do some checking.

Thank you!

**Comment by 1602** [comment]
@haas85 yep, that'd help if you post here if there are any outstanding issues with 1.0.0, or close issue if everything is fine 🤞

**Comment by haas85** [comment]
Hello,

I have been using it in a project and I have just realised about a bug related to node-sqlite3 lib. When I execute 'npm install whateverPKG' I get the error comented on this issue: https://github.com/mapbox/node-sqlite3/issues/866

I have updated manually the sqlite3 module in this module to 3.1.13 (currently you are using 3.1.8) and it looks that now doesn't fail anymore. Can you check that?

Thank you

**Comment by scottohara** [comment]
Any chance you could bump the `sqlite3` dependency from:

`"sqlite3": "=3.1.8"`

to:

`"sqlite3": "=3.1.13"`?

(or better yet `"sqlite3": "~3.1.8"`, so that any versions between `>=3.18 and < 3.2.0` are valid?)

`sqlite3@3.1.8` currently fails to build with `node@9.5.0` on macOS 10.13.3 (and besides, that version is nearly 18 months old at this point)

Also, the prebuilt binary for `3.1.8` (https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v59-darwin-x64.tar.gz) currently returns a `403` error, forcing `npm` to attempt to compile from source when installing (which then fails).

The prebuilt binary for `3.1.13` (https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v59-darwin-x64.tar.gz) downloads fine, and avoids the need to compile from source, so installs much faster.

**Comment by ppasler** [comment]
It would be great to bump to sqlite3@3.1.13, also fails in Ubuntu

**Comment by konrad-garus** [comment]
According to their reelase log, sqlite3@3.1.8 is not compatible with Node 8. That's why there is no prebuilt binary for it. Please bump sqlite3 to 3.1.13 or make the dependency less strict (e.g. with ~).
